import streamlit as st
from issue_formatter import generate_issue_content

st.set_page_config(page_title="AI MCP Issue Assistant")

st.title("AI MCP Issue Assistant")

st.write(
    "Paste a rough requirement and generate a GitHub-ready issue using Gemini."
)

requirement = st.text_area(
    "Rough requirement",
    height=180,
    placeholder=(
        "Example: A provider sends an invoice to the insurance company. "
        "The invoice must be validated by Sumex."
    )
)

if st.button("Generate GitHub Issue"):
    if not requirement.strip():
        st.warning("Please enter a requirement first.")
    else:
        try:
            with st.spinner("Generating issue with Gemini..."):
                issue_content = generate_issue_content(requirement)

            final_issue = f"""
# AI Generated GitHub Issue

{issue_content}

---

Generated by Gemini + MCP exercise.
"""

            st.markdown(final_issue)

            st.download_button(
                label="Download as Markdown",
                data=final_issue,
                file_name="github_issue.md",
                mime="text/markdown"
            )

        except Exception as error:
            st.error(str(error))