from mcp.server.fastmcp import FastMCP

mcp = FastMCP("GitHub Issue Formatter MCP Server")


@mcp.tool()
def format_github_issue(issue_content: str) -> str:
    """
    Formats LLM-generated content into a final GitHub issue body.
    """

    return f"""
# AI Generated GitHub Issue

{issue_content}

---

Generated by Gemini + local MCP server.
"""


if __name__ == "__main__":
    mcp.run()